<?php 
 
goto nBJfU; y65Mf: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/d58fe99a006c3ad4b9e24.png" tvg-id="133.astro",DRAMA HOTPOT
"; goto SFrvR; g8rr0: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5f88f4c83df61f6896eee.png" tvg-id="SPOTV",SPOTV
"; goto JykeY; xerWK: echo "https://dcqkiaqc3sngm.cloudfront.net/CH1/masterCH1.mpd
"; goto dq5qq; hePDv: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto niKaY; zk38Q: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto o5n_Z; wmLpt: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/0c4afb9624d691ef282a4.png" tvg-id="132.astro",DRAMA HEBAT\xa"; goto wI_Qh; UM4gh: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto StgVl; YXADp: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto fWEsL; hDLmA: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/acaa5134a9a55745ffae5.png" tvg-id="326.astro",Phoenix Info News HD
"; goto Mn4hx; UC6N5: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto j17sx; aQkCm: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto bjELR; zOCxN: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/ec444fecfcb3a20cd6aa4.png" tvg-id="AstroSupersport",Astro Supersport
"; goto r9oYQ; epPzv: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto lmECD; Xll76: echo "https://dcqkiaqc3sngm.cloudfront.net/CH4/masterCH4.mpd\xa"; goto zx9W7; gAyBS: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto W6JAn; yEbd1: echo "  \xa"; goto KcSwi; XJtV3: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto PZIO0; S8Gly: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto rMjZZ; Y2BAy: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"SziYvIpv/Ytcs0p82QbcNQ", "kid":"n7/9H/ITQBaaWhFCvPTdrQ" }], "type":"temporary" }
"; goto PnRa9; IZWpy: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto WQ9Gg; wXF2j: echo "  
"; goto gEcUw; cOBmQ: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/0a1e0b802beb7be122f38.png" tvg-id="4.astro",Jelly Jam World\xa"; goto pUmG0; DVpgC: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"d/ZWTWoqiWiVgbvEaF2fug", "kid":"ngdsLhf9SLS+J83Aj+IYfw" } ], "type":"temporary" }
"; goto jRddD; Gfwfv: echo "  
"; goto sg4eI; NrwOX: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/0ff4fd815a54861a9f45c.png" tvg-id="551.astro", Global Trekker
"; goto tpHzh; gEcUw: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto W5l4v; cFRSZ: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/bdb04ae013c6d829c3851.png" tvg-id="AstroSupersport2",Astro Supersport 2\xa"; goto AeodW; XwcmT: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto MbvAn; AeodW: echo "https://d3j4fjrwclc3o8.cloudfront.net/CH4/masterCH4.mpd\xa"; goto StMh4; y8qiA: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto p4L3N; vPIsq: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto UKy4h; jmY8R: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto YtKmR; taRlS: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/463016c93514bbbbca3c9.png" tvg-id="6.astro",TAYO+
"; goto gFbFY; B9nMv: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"WwDUNB6QswIrXlcTmuirFg", "kid":"SiZ7oJs6Q5aTZO53923WIg" }], "type":"temporary" }\xa"; goto WjSet; j87Aa: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"BlwQgpbXjVGoVEzEKhqnaA", "kid":"/ElXO0+WS+C0BTRJjOjWLg" } ], "type":"temporary" }
"; goto ttm6n; knjXf: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"xPNRHhKT5X4xz0IoNVUaag", "kid":"bvJHEbeaTBOk/m1Ndg2EPA" } ], "type":"temporary" }\xa"; goto JZbHF; P00Oi: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/ef2daa3ec829e54a6e13d.png" tvg-id="5.astro",Pet Club
"; goto obWwB; MXLK8: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto P2aTt; lWFno: echo "https://d1fk7kbmz4il3.cloudfront.net/CH5/masterCH5.mpd
"; goto KcSot; Xm3GX: echo "  
"; goto gC7ba; cqiyQ: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto EACDg; wSmr_: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto SzSmv; tlDlo: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto FXGuS; NSF1U: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"MzelSiFBhegbrXJyLYBAPg","kid":"jRzcbupSRsqLETsmxapKQw"}],"type":"temporary"}\xa"; goto Kk63E; IBewz: echo "https://linear10-playback.sooka.my/CH1/masterCH1.mpd\xa"; goto RpFPr; sFnzs: echo "https://linear05-playback.sooka.my/CH2/masterCH2.mpd
"; goto QK3gy; QwpCQ: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"zWfk+67JzZLoR5X7nymAcg","kid":"yZv161y8TI+G+/tA4aKwZQ"}],"type":"temporary"}\xa"; goto tUyS0; cDhjD: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto CnEiG; klw6w: echo "https://b27a6dd8a86c3e4ba93fbae22aaaac64.pmqrop.channel-assembly.mediatailor.ap-southeast-1.amazonaws.com/v1/channel/FAST_5/dash.mpd
"; goto bYDoe; gUJ20: echo "https://d3j4fjrwclc3o8.cloudfront.net/CH3/masterCH3.mpd
"; goto pqOo0; DC29e: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"NY+SYxfeT9aO+e5sI9XmlQ", "kid":"433koxZ5QEONqMhUeVvHdw" } ], "type":"temporary" }\xa"; goto xYEQm; wqp79: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto V7641; NSr3m: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto xpJSx; tPTe6: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto qy7xy; daiGH: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto qydn0; PB_v8: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto PvcQH; xpJSx: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto j87Aa; qa1DC: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto skmOL; LN3Bs: echo "https://linear13-playback.sooka.my/CH2/masterCH2.mpd\xa"; goto OUyHZ; tXntb: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto SqFUN; gcLKn: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto AAsfF; KSzGZ: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00223-unisysinfo-yrf-music-dash-sooka/index.mpd\xa"; goto OutbN; kwO2D: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto UC6N5; QRVhc: echo "https://linear12-playback.sooka.my/CH2/masterCH2.mpd
"; goto jAyXy; p06Dh: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Rt7mW; Hsc_B: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto Rln7_; cTbP1: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/4d0a8c3434f44f8a46573.png" tvg-id="KBSWorld",KBS World
"; goto jmzP3; lGpjp: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5715a7286a67669db999f.png" tvg-id="620.astro", CBeebies
"; goto GiEC3; rYfw0: echo "https://linear10-playback.sooka.my/CH2/masterCH2.mpd\xa"; goto JvbbW; wwJfR: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"GZBKr+idRaQB1cqtnYQadw", "kid":"T8ES+SqfTrmJob14DT495g" } ], "type":"temporary" }\xa"; goto K8DkK; PkF82: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Y2BAy; BPtlv: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto ra4A4; o8Qca: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto o0Qcc; Zi52Q: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"Po90DuQwygkKnK0KDQrpfA","kid":"LkC1SSAjT8utpdXHk453UQ"}],"type":"temporary"}
"; goto RiuhE; bZa1F: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto GxEBQ; ra4A4: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto itgvC; JZK1z: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto YQloH; P7kKM: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto EyvWf; UDgvR: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/670c09c6465e840e4e566.png" tvg-id="K-Plus",K-Plus\xa"; goto sPwlV; AP8uX: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto UM4gh; IojV6: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto BrfrL; fR73G: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto q07SV; o0Qcc: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"ubYV/h3VVgYX3hkdJTwCvA", "kid":"5Uay6K31Toe3u2wM1szC2g" }], "type":"temporary" }\xa"; goto ypskM; cw43a: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto jmY8R; uAghi: echo "https://linear13-playback.sooka.my/CH3/masterCH3.mpd
"; goto pMooz; JZbHF: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/ab4779ded9411f381bd84.png" tvg-id="311.astro",Astro AOD\xa"; goto auQv7; ed4Go: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto HftTS; iikXz: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto dG0Ud; twZrA: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto rpTzx; w1x3z: echo "https://d277c08tzca9og.cloudfront.net/CH1/masterCH1.mpd
"; goto ZoCjs; TghY7: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5f83d4104ac9817a9b239.png" tvg-id="503.astro",CGTN HD
"; goto DnV2J; pQhRk: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/b641200da0212a83a4f53.png" tvg-id="136.astro",Oh My Ceria
"; goto B15_0; ifv5E: echo "  
"; goto TJ9v8; Jtlqh: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"QfI0+4hZCvOw0iQRGmG/cQ", "kid":"jx2jmTJSR+ymrN17r7lfog" }], "type":"temporary" }
"; goto cFRSZ; QRVRM: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto fz3j1; xsfYm: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto AP8uX; dMz7E: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/cfc9e70ed92b4ef8e8c1d.png" tvg-id="12.astro",Tastemade\xa"; goto bhx1q; dthA1: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"268WzBXKOAtPdM13+X3GbA","kid":"ueUsgFrxQ7y/Inkw4xz96Q"}],"type":"temporary"}
"; goto wPnec; cwTqR: echo "https://d1yws6emo43ny.cloudfront.net/CH4/masterCH4.mpd
"; goto anxLe; Uc0ES: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"+TZMA5oAfez1lcmKWMMjCQ", "kid":"fLhAK8wnRmOYFYmFcQMnNA" } ], "type":"temporary" }
"; goto UDgvR; njEqg: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"4ojjMKH4k09wLmaH3df+yw", "kid":"rmrD9jQZTySNIufwwJO6cA" } ], "type":"temporary" }\xa"; goto AC_PW; zhR8s: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto tJfUR; Uj_m0: echo "  
"; goto gc2pd; nQfCb: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg02873-kravemedia-mtrspt1-sooka-dash-sooka/index.mpd\xa"; goto gxezn; RepHC: echo "  
"; goto P7kKM; AcEqI: echo "  #KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto mt_7L; xZZyc: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"xZPC7upidCKFuZ5Nh7HISg", "kid":"qOsPFSxuQpynpT85mq3yVw" } ], "type":"temporary" }
"; goto kggng; Me25a: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto a7MAf; yiNcc: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"x56Rb533occYBeOc2jDZOw", "kid":"n5n/otJ6TPugW4O5HbhG3w" }], "type":"temporary" }
"; goto mfLCk; UhfQk: echo "https://d1yws6emo43ny.cloudfront.net/CH5/masterCH5.mpd
"; goto nPJqn; wPnec: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/34c852f11f68f59af5699.png" tvg-id="701.astro",AXN HD\xa"; goto IJZvt; Oxy2U: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/669b22c4fd46abd9ca4f8.png" tvg-id="3.astro",MTRSPT1\xa"; goto nQfCb; bxZs0: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"Q9DpRhHrixCC3qY/JiP1dw","kid":"EbV3VQkcQDah00TnDjUtcg"}],"type":"temporary"}
"; goto lGpjp; ZT_BH: echo "  
"; goto ATGtc; Uuroy: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/1e15632be0a2240ef732c.png" tvg-id="554.astro",BBC Earth
"; goto LN3Bs; ZIxea: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto idjzZ; kcZmf: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto rSByo; LQhcL: echo "  \xa"; goto wSmr_; PmQ0l: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto qa1DC; RpFPr: echo "  
"; goto XJtV3; RfIu0: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"hsLWIm312SenwadaSIf4fA","kid":"AH8s5nWHSxCvxgkEagCd/A"}],"type":"temporary"}\xa"; goto pRM0L; StgVl: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"uOkanQqlnHxVmGwq5qtvZA", "kid":"SxonztiBTmWnYRg+1uT85g" } ], "type":"temporary" }
"; goto Ubhsq; lurb3: echo "https://d3ey18635ukr4v.cloudfront.net/CH1/masterCH1.mpd
"; goto cqiyQ; I2JKp: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto QwpCQ; HftTS: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto Uc0ES; IoS79: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto p_7kp; XIC3A: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto yKkPD; bj7Gc: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/ed43468ae09f6fc2c6bd9.png" tvg-id="513.astro",Al Jazeera English HD\xa"; goto AHgbx; QEW92: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/1ff29df0932fb7ad48ce3.png" tvg-id="706.astro",HITS HD\xa"; goto jzyVD; DKG_f: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto qoCYM; iLyKP: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto fie43; hLIWL: echo "https://d3j4fjrwclc3o8.cloudfront.net/CH2/masterCH2.mpd
"; goto lFjYs; NEVoX: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto YqYqv; LAFip: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"eTnjNb+Mu9aIL59cnN6+GQ", "kid":"mWhVRUkdQLSTs6SyY8ckXg" }], "type":"temporary" }
"; goto z0aBM; bYDoe: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto NSr3m; ieOVq: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto R4FWL; OutbN: echo "  
"; goto daiGH; z6JGz: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto JRnh2; PWR5H: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"zWfk+67JzZLoR5X7nymAcg","kid":"yZv161y8TI+G+/tA4aKwZQ"}],"type":"temporary"}
"; goto Uuroy; cIlIp: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto DpQs6; DpQs6: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto hePDv; bV1bg: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"ckOT6D0LbLAaL/S6sqKLxA","kid":"z++3hRtXT1KiSBMs74mo2w"}],"type":"temporary"}\xa"; goto SfXhh; ISj7A: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto nu81L; rpTzx: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto Rt8zp; gxezn: echo "  
"; goto UWJ21; zt8RY: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://iili.io/1NC5v9.png" tvg-id="ONE",One HD
"; goto LjovA; jAyXy: echo "  
"; goto IZWpy; Rln7_: echo "#EXTINF:-1 group-title="Sooka" tvg-logo="https://telegra.ph/file/e711100096d172ddc8928.png" tvg-id="11.astro",YRF Music
"; goto KSzGZ; hin7H: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"dWUwh+p3kjJOizf9XdAnnw","kid":"5k3uC5JSQtiba4J0rwsthA"}],"type":"temporary"}
"; goto yHz85; P8GGK: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto lLvr4; sV9W_: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto H18Kb; Mn4hx: echo "https://linear13-playback.sooka.my/CH1/masterCH1.mpd\xa"; goto yEbd1; xu1sx: echo "https://linear08-playback.sooka.my/CH2/masterCH2.mpd\xa"; goto LQhcL; WZA1Y: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/e5f799e7bb561e6234e5b.png" tvg-id="106.astro",Astro Oasis HD\xa"; goto aSEfW; ADdfY: echo "  \xa"; goto PVWPZ; WjSet: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/b9bcb8b113bc1e58e50bb.png" tvg-id="beINSports3",Astro Cricket Plus\xa"; goto sFnzs; JRnh2: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto twZrA; PVWPZ: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto Z3i40; xA63l: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto wvVuZ; ADEji: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"+R76Z2G2ei9U89YSmHfLaw","kid":"HiYEzRjYQjSukQr/bd6Fng"}],"type":"temporary"}
"; goto czGEc; ag2sY: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"fyDO3UFf7yr9P6YcmIfNQQ","kid":"vdJUXGfHS9+UbiE+3+JiJQ"}],"type":"temporary"}\xa"; goto NrwOX; qy7xy: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto ISj7A; OUyHZ: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto BKTuG; SzSmv: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto wwY0G; eOPvs: echo "https://linear05-playback.sooka.my/CH4/masterCH4.mpd\xa"; goto XH5df; TBQwp: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"qtosuCCLhbJxrcmyT4MSWg", "kid":"Wa0gWlhRQDmr6UD+G9K8lQ" } ], "type":"temporary" }\xa"; goto VIIPN; BfUML: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto XIC3A; Ooyvu: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto C_tCb; tefTb: $iHay5 = ["http" => ["header" => "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36\xd\xa"]]; goto yaw_c; ta3kn: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/1621221a6795938224b62.png" tvg-id="134.astro",LAWAK SENTRAL
"; goto f9T_g; zx9W7: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto XyNdV; K6IGn: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"CabPBCTxDnbaSsMHt+f/BA", "kid":"JK6Gd03wQo+0bxU+gWZGYg" } ], "type":"temporary" }
"; goto jlptE; EavSD: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto uWZPf; yKkPD: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto GyHGj; iJUsI: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto Hsc_B; ISyw9: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto r6a8s; lLvr4: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"+xL2YdZA5OvfOOMSMCJg6w", "kid":"vaf3S4QvTw6xQjldrdkfBw" }], "type":"temporary" }\xa"; goto F6UFV; PVBWa: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"KsTvR0StICr8wuhz19w5Fg", "kid":"4r0pp0ZaSuSGp1ACMFgKbg" }], "type":"temporary" }\xa"; goto g8rr0; Eg9bj: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/fee0eec440200aabe6685.png" tvg-id="AstroSupersport3",Astro Supersport 3\xa"; goto lurb3; fWEsL: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto ieOVq; Vkr9o: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto PB_v8; DLQNR: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01077-gustoworldwidem-gustotv-dash-sooka/index.mpd
"; goto ylcgl; GwDPr: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto NEVoX; Dv3ER: echo "https://linear09-playback.sooka.my/CH4/masterCH4.mpd\xa"; goto RepHC; H78E3: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/01d964c23e6ac296490a4.png" tvg-id="tvN",tvN\xa"; goto IK7Bl; oLuzL: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"JK1H9zyM//xpYdR6pVG4gg", "kid":"G15RVjjeQkO2ukmEPQvnYw" }], "type":"temporary" }
"; goto ZqvbZ; za_q7: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto ADEji; UKy4h: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto NSF1U; EeRtP: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto KWAeG; xBvVH: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto ULyej; PRD6D: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto xBvVH; YaxfX: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/071ec21b298280a2e418c.png" tvg-id="135.astro",TRAVEL & TASTE\xa"; goto klw6w; tig3d: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto PVBWa; dRTDG: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto K6IGn; tj8BX: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto UDrRi; D__FL: echo "  
"; goto P95HY; uvBu_: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/a753f71d686cef4de067e.png" tvg-id="808.astro",SPOTV Stadia\xa"; goto Akm8h; yQh_W: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/ee9f952ab359e6bc756b6.png" tvg-id="612.astro", Dreamworks
"; goto uAghi; JykeY: echo "https://d1fk7kbmz4il3.cloudfront.net/CH2/masterCH2.mpd
"; goto ZIxea; p4L3N: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto RfIu0; UiJti: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto gAyBS; Kk63E: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/1bd44ed23f0b2e4ef52d5.png" tvg-id="515.astro",CNA HD\xa"; goto QKRG4; Kl7O6: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto DKG_f; aaTYM: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto wqp79; P95HY: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto BVp3V; dZbpN: echo "https://b27a6dd8a86c3e4ba93fbae22aaaac64.pmqrop.channel-assembly.mediatailor.ap-southeast-1.amazonaws.com/v1/channel/FAST_2/dash.mpd\xa"; goto mE3ZW; X69Ev: echo "https://linear08-playback.sooka.my/CH1/masterCH1.mpd
"; goto hRGRf; jRddD: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5d45ee71e76d1e0d19199.png" tvg-id="OKEY",TV Okey\xa"; goto xu1sx; K8DkK: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/91b060a9fbca0526d338f.png" tvg-id="AstroAwani",Astro Awani\xa"; goto ebaak; q07SV: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto epPzv; XH5df: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto Vkr9o; QTRrE: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto y65Mf; ypskM: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5e4a76a2f67d30080d63f.png" tvg-id="beINSports3",beIN Sports 3
"; goto Y2MXp; UKuI8: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto oLuzL; VGDEQ: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto IojV6; itgvC: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto mAkXD; wwY0G: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto wmLpt; KWAeG: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto yy_rY; bjELR: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto wITPM; Rt7mW: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"VYm6JmXI2v2p+5fz1+9Sbg","kid":"bxWpsvJ7StqpWQUNtgPAjw"}],"type":"temporary"}\xa"; goto uvBu_; JP5hK: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/e36872d8b3f54568fdcbb.png" tvg-id="AstroAEC",Astro AEC
"; goto U7JLT; tpHzh: echo "https://linear14-playback.sooka.my/CH1/masterCH1.mpd
"; goto p3rtQ; ebaak: echo "https://linear03-playback.sooka.my/CH5/masterCH5.mpd\xa"; goto ywT6E; uWZPf: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto dRTDG; c7fJx: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto UKuI8; UDrRi: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto XvXua; MbvAn: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto njEqg; nNjCQ: echo "  \xa"; goto PiaL1; ENtKr: echo "  \xa"; goto cIlIp; dvrhw: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto DC29e; DPamM: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01553-blueantmediaasi-freemovies-dash-sooka-sooka/index.mpd\xa"; goto QGADj; qydn0: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto Oxy2U; V7641: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5519c33486348b23ffeca.png" tvg-id="9.astro",Gusto TV\xa"; goto DLQNR; GmfTU: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"lofZG3/WR6iBg9CkzJJfdw", "kid":"s8z3OnpmT4WudBE2f/svpw" }], "type":"temporary" }\xa"; goto zOCxN; qVCHG: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto B2vYt; oLSdT: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto tig3d; F6UFV: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/4cf5891aa6569231ea9a8.png" tvg-id="AstroSupersport4",Astro Supersport 4
"; goto hLIWL; bAatX: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto pNfpN; SbuAs: echo "https://linear10-playback.sooka.my/CH3/masterCH3.mpd\xa"; goto Uj_m0; PZIO0: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto EpBxI; BrfrL: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"p4q3pLjyp0Zjf9C/iAiEOA", "kid":"pGCE+WsDTiCj1kfwp76NXA" } ], "type":"temporary" }\xa"; goto ZSjPE; W5l4v: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto adutU; fAB8S: echo "https://linearfast06.playback.sooka.my/v1/dash/7d6144f66f990e10fc667942d522b82f89ae5cd9/FAST_6_Ad/dash.mpd
"; goto jsG2L; RiuhE: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/4a10b804de489dfe818af.png" tvg-id="335.astro",CCTV4 HD
"; goto SbuAs; o5n_Z: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto Wpy7_; anxLe: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto EavSD; qtfId: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto LAFip; YQloH: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto awJAX; sPwlV: echo "https://linear08-playback.sooka.my/CH5/masterCH5.mpd
"; goto BPtlv; PvcQH: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"xN10vdm0ZXlLH7Eqq2WW+A", "kid":"rPtLDx9ZRr+nw/LnwtYNAA" } ], "type":"temporary" }
"; goto QEW92; gC7ba: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto vPIsq; qB853: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/86f0c6bc32983a530650f.png" tvg-id="8.astro",Infamous TV
"; goto wKyj3; ZSjPE: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/7f3f3c64928e57133a1e0.png" tvg-id="317",TVB Entertainment News HD\xa"; goto Dv3ER; Y5WLN: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto YaxfX; UWJ21: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto s14P2; U7JLT: echo "https://d1yws6emo43ny.cloudfront.net/CH1/masterCH1.mpd\xa"; goto z6JGz; sg4eI: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto yGt19; r9oYQ: echo "https://d3j4fjrwclc3o8.cloudfront.net/CH1/masterCH1.mpd\xa"; goto RsIqY; XvXua: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Qg4ID; wI_Qh: echo "https://b27a6dd8a86c3e4ba93fbae22aaaac64.pmqrop.channel-assembly.mediatailor.ap-southeast-1.amazonaws.com/v1/channel/FAST_1/dash.mpd\xa"; goto fR73G; Ubhsq: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/017abfae80104df23085c.png" tvg-id="tvNMovies",tvN Movies
"; goto AmNO9; QK3gy: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto MXLK8; pRM0L: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/1f94653020273c36a030e.png" tvg-id="325.astro",Phoenix Chinese Channel HD\xa"; goto lJTw3; i0CIu: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"O+3QvNEXVgFsmjzL559mZQ", "kid":"xeZBeMM+QYWjQG2EJSzXoA" }], "type":"temporary" }
"; goto Eg9bj; kNWEQ: echo "  \xa"; goto iJUsI; PiaL1: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto zk38Q; EpBxI: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto knjXf; P2aTt: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/0c41a0b455c9348edb392.png" tvg-id="7.astro",Free Movie\xa"; goto DPamM; D8p9L: echo "https://dcqkiaqc3sngm.cloudfront.net/CH5/masterCH5.mpd
"; goto Me25a; yuPts: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto PWR5H; kSujv: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto Kti1p; WQ9Gg: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto AOr_o; W_whP: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto azww5; xKXvx: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/8ad97b76073e147cdeaa1.png" tvg-id="AstroQJ",Astro QJ
"; goto cwTqR; Y2MXp: echo "https://dcqkiaqc3sngm.cloudfront.net/CH2/masterCH2.mpd
"; goto sxcqZ; AHgbx: echo "https://linear12-playback.sooka.my/CH1/masterCH1.mpd
"; goto Xm3GX; A08f6: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto GmfTU; obWwB: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-petclub-astro-dash-sooka/index.mpd
"; goto ISyw9; E8pfA: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/a449990e1f2d0a6ac8ec6.png" tvg-id="TV2",TV2\xa"; goto X69Ev; viG1R: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto XwcmT; sxcqZ: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto Kl7O6; Kti1p: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto A08f6; gbdem: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Zi52Q; b2k1Z: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto gbdem; mAkXD: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"tPEppE661kuiVHX9L66wMg", "kid":"ziR/uJnPTyilAR4YBpyHcg" } ], "type":"temporary" }\xa"; goto H78E3; nrjSl: echo "  
"; goto viG1R; idjzZ: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto J1GkU; Hnkku: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto zhR8s; tUyS0: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5b8c41513424d1b154a88.png" tvg-id="717.astro",BBC Lifestyle HD
"; goto QRVhc; B15_0: echo "https://linearfast07.playback.sooka.my/v1/dash/7d6144f66f990e10fc667942d522b82f89ae5cd9/FAST_7_Ad/dash.mpd\xa"; goto ENtKr; YqYqv: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"0HNv8GRw6YQQgfQA4GNyFA","kid":"GUUd3198TxWiC0y/WIdXOg"}],"type":"temporary"}
"; goto yQh_W; j17sx: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"xSfUpbPUNkMSpOeLnenogA", "kid":"XLBdFMjdRWO5VuN9Cg8Rdw" }], "type":"temporary" }
"; goto XZCED; fAkAT: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto iLyKP; FigwD: echo "https://linear10-playback.sooka.my/CH4/masterCH4.mpd
"; goto ADdfY; QGADj: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto JvcF8; McLQJ: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto YeglI; KcSot: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto kSujv; jzyVD: echo "https://linear05-playback.sooka.my/CH5/masterCH5.mpd\xa"; goto tj8BX; qoCYM: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto B9nMv; bhx1q: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00047-tastemade-tastemadeintlaus-dash-sooka/index.mpd
"; goto LFSWl; fz3j1: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto EVG1E; DnV2J: echo "https://linear11-playback.sooka.my/CH3/masterCH3.mpd\xa"; goto Gfwfv; W6JAn: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Jtlqh; mt_7L: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto dMz7E; AAsfF: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto McLQJ; czGEc: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/b400ba4cddee51706c418.png" tvg-id="316.astro",CTI Asia HD\xa"; goto FigwD; H18Kb: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto PkF82; f0GH6: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto oLSdT; ULyej: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto dthA1; a7MAf: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto kwO2D; CnEiG: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"YdE0MzWw3b+r4oGNlS/gZg", "kid":"RGeTkQFyTPeWOjLKvPenwA" } ], "type":"temporary" }\xa"; goto lFmzv; u8kFY: echo "https://d1fk7kbmz4il3.cloudfront.net/CH1/masterCH1.mpd
"; goto Hnkku; rSByo: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto dvrhw; vP2Of: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto Y5WLN; YeglI: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"UGsB5FPcqbzg3Ag+0B/MQA", "kid":"8NnVKgwkRB2zzoLvypx4Pg" } ], "type":"temporary" }\xa"; goto WZA1Y; IJZvt: echo "https://linear11-playback.sooka.my/CH4/masterCH4.mpd
"; goto tXntb; ATGtc: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto VGDEQ; AHGiE: echo "https://dcqkiaqc3sngm.cloudfront.net/CH3/masterCH3.mpd\xa"; goto EeRtP; dpD14: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto P8GGK; RsIqY: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto UiJti; kggng: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/a5407d65397a96458214f.png" tvg-id="824.astro",Astro Cricket\xa"; goto UhfQk; pqOo0: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto f0GH6; lmECD: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/6c1ea8ba4e4fd18681306.png" tvg-id="131.astro",FILEM MANTAP
"; goto dZbpN; GxEBQ: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto i0CIu; nqjMA: echo "https://linear12-playback.sooka.my/CH4/masterCH4.mpd\xa"; goto PRD6D; YRPY2: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto hin7H; azww5: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto bV1bg; J1GkU: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto xA63l; XyNdV: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto EZHtf; rMjZZ: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto QTRrE; yaw_c: $N06vp = file_get_contents($DqUw5); goto BfUML; QKRG4: echo "https://linear12-playback.sooka.my/CH3/masterCH3.mpd\xa"; goto ifv5E; Il8g9: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"5hbmpnJ5zVru7DPM6eLHjQ","kid":"wYaJZ34KRiuUparLy8cddA"}],"type":"temporary"}
"; goto TghY7; AmNO9: echo "https://linear08-playback.sooka.my/CH4/masterCH4.mpd\xa"; goto PmQ0l; dq5qq: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto hweIm; EACDg: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto dpD14; ZoCjs: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto a5Ra5; wsGzO: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto jfJR6; Wpy7_: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"6GP3FJ5S91Jr90QDTifOjQ", "kid":"977qwgCvQNWIbf6Y1y/PyA" } ], "type":"temporary" }\xa"; goto E8pfA; wvVuZ: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"ZfiPZoUB9++nXCW+WY90Vg", "kid":"pXcYTtbGRWC+uHyW7nj3uA" }], "type":"temporary" }\xa"; goto QKMB7; mE3ZW: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto iikXz; SfXhh: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/fdf5dc4c972b4b3350667.png" tvg-id="300.astro",iQIYI HD\xa"; goto nqjMA; LVqjI: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto vP2Of; AC_PW: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/8b00ee775c388fc38469c.png" tvg-id="TVBClassic",TVB Classic HD
"; goto oiC4k; r6a8s: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto cOBmQ; pUmG0: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01553-blueantmediaasi-jellyjam-dash-sooka-test-sooka/index.mpd\xa"; goto rwifb; H5ch4: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/bf3c99a8a7c2b8aae472c.png" tvg-id="AstroArenaBola",Arena Bola
"; goto u8kFY; rwifb: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto W_whP; f9T_g: echo "https://b27a6dd8a86c3e4ba93fbae22aaaac64.pmqrop.channel-assembly.mediatailor.ap-southeast-1.amazonaws.com/v1/channel/FAST_3/dash.mpd\xa"; goto S8Gly; p_7kp: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[{ "kty":"oct", "k":"4dQox/HKgjOabPodB1dCjg", "kid":"dIHT43OMRnaPE44gj+6Qdg" }], "type":"temporary" }
"; goto H5ch4; PnRa9: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/d94c1cdf66541be72786b.png" tvg-id="beINSports",beIN Sports
"; goto D8p9L; skmOL: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto wwJfR; HXk3Q: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto GwDPr; jsG2L: echo "  
"; goto Ooyvu; StMh4: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto c2gdk; TJ9v8: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto b2k1Z; yy_rY: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto p06Dh; wKyj3: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01324-infamousmedia-infamoustv-dash-sooka/index.mpd\xa"; goto kNWEQ; bnRB1: echo "https://linear11-playback.sooka.my/CH2/masterCH2.mpd\xa"; goto g_utT; AeoAq: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto ajILd; a5Ra5: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}
"; goto c7fJx; gc2pd: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto y8qiA; EVG1E: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto yiNcc; JvcF8: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto P00Oi; p3rtQ: echo "  \xa"; goto HXk3Q; EyvWf: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto cDhjD; ajILd: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"D1azPU2+4uYlt6ZiFt1Y3Q","kid":"rELqZssITzqweJyipX/ubA"}],"type":"temporary"}\xa"; goto hDLmA; wITPM: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto DVpgC; d2MEI: echo "https://linear05-playback.sooka.my/CH3/masterCH3.mpd\xa"; goto cw43a; Akm8h: echo "https://d3pjpbn7s5952i.cloudfront.net/CH1/masterCH1.mpd\xa"; goto tPTe6; g_utT: echo "  
"; goto YXADp; hweIm: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto mbAvZ; ql7KQ: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/670a6c2c2f87754f6c8ec.png" tvg-id="TV1",TV1
"; goto IVguz; mSBuT: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"51Fl04uQlWfAM1OuSye2+A", "kid":"AesRaCCJQPiycLTgmUVw5w" } ], "type":"temporary" }\xa"; goto JP5hK; GiEC3: echo "https://linear13-playback.sooka.my/CH4/masterCH4.mpd
"; goto wXF2j; xYEQm: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/390db16ccf28ea54c4cc7.png" tvg-id="TVBJade",TVB Jade\xa"; goto aYveO; nBJfU: $DqUw5 = "https://bosiptv.com/live/sp/id.php"; goto tefTb; FXGuS: echo "#EXTINF:-1 group-title="Sooka" tvg-logo="https://telegra.ph/file/e711100096d172ddc8928.png" tvg-id="11.astro",Astro YRF Music
"; goto Fu0Xt; Z3i40: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto AeoAq; k55ft: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/45ebb716daee3d1107421.png" tvg-id="TVS",TVS
"; goto rYfw0; LFSWl: echo "  \xa"; goto aaTYM; lFmzv: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/2f2b64e9f0dd2dc964361.png" tvg-id="319.astro",TVB Xing He HD\xa"; goto IBewz; ZqvbZ: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/4dd8b7db6182cb5f48ce5.png" tvg-id="AstroArena2",Astro Arena 2\xa"; goto xerWK; yGt19: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto pQhRk; awJAX: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"kDHO+thTx4plwgIIIVMvPQ", "kid":"5VhM/9YVSROXuM3tXmecGQ" } ], "type":"temporary" }\xa"; goto cTbP1; jmzP3: echo "https://linear03-playback.sooka.my/CH1/masterCH1.mpd
"; goto N5HkT; ywT6E: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto tlDlo; nPJqn: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto sV9W_; R4FWL: echo "#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","k":"MXMN67RxFHXCLn6wv9osew","kid":"wDQGo+6AQXui/y5g7rLehA"}],"type":"temporary"}
"; goto bj7Gc; Rt8zp: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"AiI5ZeM/e/HmwhJ4Bju1CA", "kid":"sOfb4l5sSfm1JeYU/EqmDA" } ], "type":"temporary" }
"; goto xKXvx; SqFUN: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto yuPts; EZHtf: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto o8Qca; nu81L: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto xZZyc; dG0Ud: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto ta3kn; VIIPN: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/94a14183b17e8749173fa.png" tvg-id="401.astro",HITS MOVIES HD\xa"; goto eOPvs; pMooz: echo "  
"; goto wsGzO; niKaY: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"/2UXT47F1MiOjYohloVjzw", "kid":"DW0qGsjRThmxdFVlB3DNmQ" } ], "type":"temporary" }
"; goto k55ft; AOr_o: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto bxZs0; lN2IO: echo "  
"; goto gcLKn; BKTuG: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto I2JKp; s14P2: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto qVCHG; fie43: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/98fb95419ca16069cfce4.png" tvg-id="130.astro",Jom Ngaji
"; goto fAB8S; ylcgl: echo "  
"; goto ZWnOi; mfLCk: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/f3d65152120615b6eef9b.png" tvg-id="W-Sport",W-Sport\xa"; goto gUJ20; pNfpN: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto Il8g9; lJTw3: echo "https://linear11-playback.sooka.my/CH1/masterCH1.mpd\xa"; goto D__FL; GyHGj: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey
"; goto mSBuT; IVguz: echo "https://linear08-playback.sooka.my/CH3/masterCH3.mpd
"; goto nNjCQ; IK7Bl: echo "https://linear03-playback.sooka.my/CH4/masterCH4.mpd\xa"; goto xsfYm; XZCED: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/8b9be78d45d64af83200c.png" tvg-id="beINSports2",beIN Sports 2\xa"; goto Xll76; yHz85: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/93211594d20f9ea471ec9.png" tvg-id="550.astro",Love Nature HD
"; goto bnRB1; N5HkT: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto ed4Go; ZWnOi: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto uMPK6; QKMB7: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/5cbed7dd2c3a6d7d93391.png" tvg-id="SPOTV2",SPOTV2\xa"; goto AHGiE; c2gdk: echo "#EXTHTTP:{"Authorization":"Bearer {$N06vp}"}\xa"; goto bZa1F; oiC4k: echo "https://linear09-playback.sooka.my/CH2/masterCH2.mpd\xa"; goto ZT_BH; F7NrF: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto JZK1z; auQv7: echo "https://linear07-playback.sooka.my/CH5/masterCH5.mpd\xa"; goto lN2IO; YtKmR: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto TBQwp; LjovA: echo "https://linear05-playback.sooka.my/CH1/masterCH1.mpd\xa"; goto F7NrF; lFjYs: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive\xa"; goto QRVRM; adutU: echo "#KODIPROP:inputstream.adaptive.license_type=org.w3.clearkey\xa"; goto ag2sY; jfJR6: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto YRPY2; JvbbW: echo "  \xa"; goto kcZmf; gFbFY: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00640-lydnetwork-tayoplus-dash-sooka/index.mpd
"; goto AcEqI; SFrvR: echo "https://b27a6dd8a86c3e4ba93fbae22aaaac64.pmqrop.channel-assembly.mediatailor.ap-southeast-1.amazonaws.com/v1/channel/FAST_4/dash.mpd
"; goto LVqjI; z0aBM: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/6996a6dca16f43f734049.png" tvg-id="AstroArenaBola2",Arena Bola 2
"; goto lWFno; B2vYt: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"F/ut5qlPUnGmp8VjdL9tjg", "kid":"UmLL6+rWT0KqgxfjyxMQbA" } ], "type":"temporary" }
"; goto ql7KQ; BVp3V: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto za_q7; mbAvZ: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto IoS79; KcSwi: echo "#KODIPROP:inputstreamaddon=inputstream.adaptive
"; goto bAatX; aYveO: echo "https://linear09-playback.sooka.my/CH3/masterCH3.mpd
"; goto nrjSl; C_tCb: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto taRlS; Qg4ID: echo "#KODIPROP:inputstream.adaptive.license_key={ "keys":[ { "kty":"oct", "k":"bhcdw24jVsJOTlmxm8mPxQ", "kid":"aXljcdxORX2Y+isCXqv8lA" } ], "type":"temporary" }\xa"; goto zt8RY; uMPK6: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash
"; goto qB853; tJfUR: echo "#KODIPROP:inputstream.adaptive.manifest_type=dash\xa"; goto qtfId; ttm6n: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/0cae52fdf1540e0d84455.png" tvg-id="702.astro",HITS NOW
"; goto d2MEI; jlptE: echo "#EXTINF:-1 group-logo="https://cikgusuraya.tech/rokets.png" group-title="Sooka" tvg-logo="https://telegra.ph/file/8a83953f3b1fc63e1d7a8.png" tvg-id="AstroArena",Astro Arena
"; goto w1x3z; FVRqu: echo "  \xa"; goto fAkAT; hRGRf: echo "  \xa"; goto aQkCm; aSEfW: echo "https://linear09-playback.sooka.my/CH1/masterCH1.mpd\xa"; goto FVRqu; Fu0Xt: echo "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00223-unisysinfo-yrf-music-dash-sooka/index.mpd\xa"; 
?> 